// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2xT9zXfFyqfe-Q0_PTZtWJVyuQrDqrRY',
    appId: '1:482101274371:web:c0567a30465e27657eeb36',
    messagingSenderId: '482101274371',
    projectId: 'tourease-5ce3d',
    authDomain: 'tourease-5ce3d.firebaseapp.com',
    storageBucket: 'tourease-5ce3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjTZIcCO5dE-x_S5a9fP2HMILeLaiey3w',
    appId: '1:482101274371:android:99cd4d03cade22927eeb36',
    messagingSenderId: '482101274371',
    projectId: 'tourease-5ce3d',
    storageBucket: 'tourease-5ce3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfkqsviZEn8MM7lCXZwHC0d7DCj-5sxFk',
    appId: '1:482101274371:ios:8505984fb5cd73717eeb36',
    messagingSenderId: '482101274371',
    projectId: 'tourease-5ce3d',
    storageBucket: 'tourease-5ce3d.firebasestorage.app',
    iosBundleId: 'com.tourease.tourease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfkqsviZEn8MM7lCXZwHC0d7DCj-5sxFk',
    appId: '1:482101274371:ios:8505984fb5cd73717eeb36',
    messagingSenderId: '482101274371',
    projectId: 'tourease-5ce3d',
    storageBucket: 'tourease-5ce3d.firebasestorage.app',
    iosBundleId: 'com.tourease.tourease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2xT9zXfFyqfe-Q0_PTZtWJVyuQrDqrRY',
    appId: '1:482101274371:web:eca7e7cfa41042eb7eeb36',
    messagingSenderId: '482101274371',
    projectId: 'tourease-5ce3d',
    authDomain: 'tourease-5ce3d.firebaseapp.com',
    storageBucket: 'tourease-5ce3d.firebasestorage.app',
  );
}
